### ISSUE TITLE
Add more `less`-like keybindings

### ISSUE THREAD

**Issue by quchen** [fmthoma/vgrep#23]
VGrep mimics a better `grep -C∞ | less`, so I think it should have some additional bindings that `less` has.
- <kbd>Ctrl-u</kbd>, <kbd>Ctrl-d</kbd>: go up/down half a page
- <kbd>Ctrl-b</kbd>, <kbd>Ctrl-f</kbd>: go up/down a full page
- <kbd>n</kbd>/<kbd>N</kbd> to jump to the next/previous hit in the current file

**Comment by fmthoma** [comment]
I'm a bit sceptical about `n`/`N`, since with implementing a search within the results list/pager, these would be the keys to map to `next-match`/`previous-match`. So I'm hesitating to make them default, but with #35 you can define them in your config file:

```yaml
keybindings:
    pager-keybindings:
        n: next-result
        N: prev-result
```
