### ISSUE TITLE
Make `grep` tool configurable

### ISSUE THREAD

**Issue by fmthoma** [fmthoma/vgrep#34]
E.g. in `~/.vgrep/config.yaml`:
```yaml
…
backend:
    grep-command: "grep -nH --color=always"
    recursive-grep-command: "grep -rnHI --color=always"
    …
```

Use cases:
* People who want to use `ack`/`ag` instead of `grep`
* Passing custom options (like `-i`) by default

OTOH:
Part of the functionality can simply be emulated using a shell alias:
```
alias vgrep='function __ack_vgrep() { ack --color "$@" | vgrep; }; __ack_vgrep'
```
with the restriction that some arguments (like `--help`, `--version`) will produce garbled output, and that piping (`vgrep foo | vgrep bar`) is not possible.
